# Generated by Django 3.2.8 on 2022-07-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_General', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='contenido',
            field=models.TextField(max_length=1000),
        ),
    ]
