# Generated by Django 4.0.6 on 2022-07-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_General', '0003_entry_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='preview',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='publicado',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='draft', max_length=10),
        ),
    ]
