# Generated by Django 4.0.6 on 2022-07-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_General', '0004_entry_preview_alter_entry_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='publicado',
            field=models.CharField(choices=[('draft', 'Draft'), ('publicado', 'Publicado')], default='draft', max_length=10),
        ),
    ]
