# Generated by Django 4.0.6 on 2022-07-30 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_General', '0005_alter_entry_publicado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='preview',
            new_name='muestra_inferior',
        ),
    ]
