# Generated by Django 4.0.6 on 2022-07-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_General', '0006_rename_preview_entry_muestra_inferior'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='preview',
            field=models.CharField(choices=[('draft', 'Draft'), ('publicado', 'Publicado')], default='publicado', max_length=10),
        ),
    ]
