# Generated by Django 4.0.6 on 2022-07-30 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_General', '0007_entry_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='preview',
        ),
    ]
