# Generated by Django 4.0.6 on 2022-08-14 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_General', '0011_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='post',
            new_name='blogpost_connected',
        ),
    ]
