# Generated by Django 3.2.8 on 2022-08-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_General', '0018_entry_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
