# Generated by Django 3.2.8 on 2022-08-20 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog_General', '0019_entry_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(default='Some String', max_length=200)),
                ('contenido', models.TextField(max_length=1500)),
                ('imagen', models.URLField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('publicado', models.CharField(choices=[('draft', 'Draft'), ('publicado', 'Publicado')], default='draft', max_length=10)),
                ('muestra_inferior', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=10)),
                ('muestra_superior', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=10)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('likes', models.ManyToManyField(related_name='entry_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
