# Generated by Django 3.2.8 on 2022-08-21 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_General', '0020_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='blogpost_connected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Blog_General.publicacion'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='contenido',
            field=models.TextField(max_length=3500),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
