# Generated by Django 3.2.8 on 2022-08-27 00:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog_General', '0021_auto_20220820_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='entry_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='muestra_inferior',
            field=models.CharField(choices=[('si', 'si'), ('no', 'no')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='muestra_superior',
            field=models.CharField(choices=[('si', 'si'), ('no', 'no')], default='no', max_length=10),
        ),
    ]
