# Generated by Django 3.2.8 on 2022-08-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_General', '0025_blogimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
