# Generated by Django 3.2.8 on 2022-08-28 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_General', '0026_alter_publicacion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimagen',
            name='publicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Blog_General.publicacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.URLField(blank=True, default='..', null=True),
        ),
    ]
