# Generated by Django 3.2.8 on 2022-08-28 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog_General', '0027_auto_20220828_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimagen',
            name='user',
        ),
        migrations.AlterField(
            model_name='blogimagen',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
