# Generated by Django 3.2.8 on 2022-08-28 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_General', '0028_auto_20220828_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogimagen',
            old_name='publicacion',
            new_name='user',
        ),
    ]
