# Generated by Django 3.2.8 on 2022-08-28 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_General', '0029_rename_publicacion_blogimagen_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimagen',
            name='user',
        ),
        migrations.AddField(
            model_name='blogimagen',
            name='publicacion_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog_General.publicacion'),
        ),
    ]
