# Generated by Django 3.2.8 on 2022-08-28 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_General', '0030_auto_20220828_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimagen',
            name='publicacion_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagen_blog', to='Blog_General.publicacion'),
        ),
    ]
