# Generated by Django 4.0.6 on 2022-07-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_juegos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='descripcion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juegos',
            name='urlimagen',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
