# Generated by Django 4.0.6 on 2022-08-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_juegos', '0002_juegos_descripcion_juegos_urlimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
