# Generated by Django 3.2.8 on 2022-08-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_juegos', '0004_alter_juegos_urlimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='muestra_superior',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
    ]
