# Generated by Django 3.2.8 on 2022-08-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_juegos', '0008_juegos_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='desarrollador',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='genero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='plataforma',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='urlimagen',
            field=models.CharField(max_length=50),
        ),
    ]
