# Generated by Django 3.2.8 on 2022-08-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_juegos', '0010_juegos_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='muestra_inferior',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=10),
        ),
    ]
