# Generated by Django 3.2.8 on 2022-08-22 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_juegos', '0011_juegos_muestra_inferior'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='likes',
            field=models.ManyToManyField(related_name='juegos_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
