# Generated by Django 3.2.8 on 2022-07-26 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroUsuarios', '0002_preferencias_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preferencias_Usuario',
        ),
    ]
