# Generated by Django 4.0.6 on 2022-07-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroUsuarios', '0004_preferencias_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferencias_usuario',
            options={'verbose_name': 'Preferencias'},
        ),
    ]
