# Generated by Django 3.2.8 on 2022-07-27 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroUsuarios', '0004_preferencias_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferencias_usuario',
            options={'verbose_name': 'Preferencias'},
        ),
    ]
